/** FGP Midwest MSRP kit catalog — master price sheet pages 1–4 (Apr 2026). */
/** Generated by scripts/build-products-catalog.mjs — do not hand-edit PRODUCT entries. */

export const EPOLY_PIGMENT_RETAIL_32OZ_USD = {
  "Black": 39.8,
  "Metal Gray": 40.2,
  "Medium Gray": 40.9,
  "Sable Gray": 44.3,
  "White": 52.6,
  "Dover Beige": 44.5,
  "Tan": 43.2
};

const _BASE_PRODUCTS = {
  "hyperbond_clear": {
    "name": "HyperBOND (Clear)",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 870,
        "tierPrices": {
          "small": 826.5,
          "tier2": 783,
          "preferred": 739.4
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 195,
        "tierPrices": {
          "small": 185.25,
          "tier2": 175.5,
          "preferred": 165.75
        },
        "gals": 3
      }
    ]
  },
  "hyperbond_medium_gray": {
    "name": "HyperBOND (Medium Gray)",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 900,
        "tierPrices": {
          "small": 855,
          "tier2": 810,
          "preferred": 765
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 201,
        "tierPrices": {
          "small": 190.95,
          "tier2": 180.9,
          "preferred": 170.85
        },
        "gals": 3
      }
    ]
  },
  "hyperbond_sable_gray": {
    "name": "HyperBOND (Sable Gray)",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 900,
        "tierPrices": {
          "small": 855,
          "tier2": 810,
          "preferred": 765
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 201,
        "tierPrices": {
          "small": 190.95,
          "tier2": 180.9,
          "preferred": 170.85
        },
        "gals": 3
      }
    ]
  },
  "hyperbond_tan": {
    "name": "HyperBOND (Tan)",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 900,
        "tierPrices": {
          "small": 855,
          "tier2": 810,
          "preferred": 765
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 201,
        "tierPrices": {
          "small": 190.95,
          "tier2": 180.9,
          "preferred": 170.85
        },
        "gals": 3
      }
    ]
  },
  "dt454_clear": {
    "name": "DT 454 (Clear) — Turbo same $",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 975,
        "tierPrices": {
          "small": 926.25,
          "tier2": 877.5,
          "preferred": 828.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 210,
        "tierPrices": {
          "small": 199.5,
          "tier2": 189,
          "preferred": 178.5
        },
        "gals": 3
      }
    ]
  },
  "hyperrez_uv": {
    "name": "HyperREZ UV",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 975,
        "tierPrices": {
          "small": 926.25,
          "tier2": 877.5,
          "preferred": 828.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 210,
        "tierPrices": {
          "small": 199.5,
          "tier2": 189,
          "preferred": 178.5
        },
        "gals": 3
      }
    ]
  },
  "mv2112": {
    "name": "MV 2112",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1575,
        "tierPrices": {
          "small": 1496.25,
          "tier2": 1417.5,
          "preferred": 1338.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 360,
        "tierPrices": {
          "small": 342,
          "tier2": 324,
          "preferred": 306
        },
        "gals": 3
      }
    ]
  },
  "hyperflex": {
    "name": "HyperFLEX",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "10 gal",
        "msrp": 750,
        "tierPrices": {
          "small": 712.5,
          "tier2": 675,
          "preferred": 637.5
        },
        "gals": 10
      },
      {
        "size": "2 gal",
        "msrp": 166,
        "tierPrices": {
          "small": 157.7,
          "tier2": 149.4,
          "preferred": 141.1
        },
        "gals": 2
      }
    ]
  },
  "hyperflow": {
    "name": "HyperFLOW",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 995,
        "tierPrices": {
          "small": 945.25,
          "tier2": 895.5,
          "preferred": 845.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 210,
        "tierPrices": {
          "small": 199.5,
          "tier2": 189,
          "preferred": 178.5
        },
        "gals": 3
      }
    ]
  },
  "hyperprime_mvb": {
    "name": "HyperPrime MVB — Clear",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 855,
        "tierPrices": {
          "small": 812.25,
          "tier2": 769.5,
          "preferred": 726.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 177,
        "tierPrices": {
          "small": 168.15,
          "tier2": 159.3,
          "preferred": 150.45
        },
        "gals": 3
      }
    ]
  },
  "hyperprime_mvb_pig": {
    "name": "HyperPrime MVB — Pigmented",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 960,
        "tierPrices": {
          "small": 912,
          "tier2": 864,
          "preferred": 816
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 195,
        "tierPrices": {
          "small": 185.25,
          "tier2": 175.5,
          "preferred": 165.75
        },
        "gals": 3
      }
    ]
  },
  "hydroprime_40": {
    "name": "HydroPrime 40",
    "materialCategory": "epoxy",
    "kits": [
      {
        "size": "2 gal",
        "msrp": 165,
        "tierPrices": {
          "small": 156.75,
          "tier2": 148.5,
          "preferred": 140.25
        },
        "gals": 2
      },
      {
        "size": "10 gal",
        "msrp": 924.68,
        "tierPrices": {
          "small": 878.45,
          "tier2": 832.21,
          "preferred": 785.98
        },
        "gals": 10
      }
    ]
  },
  "aspartic85_slow": {
    "name": "Aspartic 85 Slow Go",
    "materialCategory": "polyaspartic",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1425,
        "tierPrices": {
          "small": 1353.75,
          "tier2": 1282.5,
          "preferred": 1211.25
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 295,
        "tierPrices": {
          "small": 280.25,
          "tier2": 265.5,
          "preferred": 250.75
        },
        "gals": 3
      }
    ]
  },
  "aspartic85_slow_low": {
    "name": "Aspartic 85 Slow Go (Low Odor)",
    "materialCategory": "polyaspartic",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1475,
        "tierPrices": {
          "small": 1401.25,
          "tier2": 1327.5,
          "preferred": 1253.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 300,
        "tierPrices": {
          "small": 285,
          "tier2": 270,
          "preferred": 255
        },
        "gals": 3
      }
    ]
  },
  "aspartic85_fast": {
    "name": "Aspartic 85 Fast Cure",
    "materialCategory": "polyaspartic",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1425,
        "tierPrices": {
          "small": 1353.75,
          "tier2": 1282.5,
          "preferred": 1211.25
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 295,
        "tierPrices": {
          "small": 280.25,
          "tier2": 265.5,
          "preferred": 250.75
        },
        "gals": 3
      }
    ]
  },
  "aspartic85_fast_low": {
    "name": "Aspartic 85 Fast Cure (Low Odor)",
    "materialCategory": "polyaspartic",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1475,
        "tierPrices": {
          "small": 1401.25,
          "tier2": 1327.5,
          "preferred": 1253.75
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 300,
        "tierPrices": {
          "small": 285,
          "tier2": 270,
          "preferred": 255
        },
        "gals": 3
      }
    ]
  },
  "aspartic100": {
    "name": "Aspartic 100",
    "materialCategory": "polyaspartic",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1550,
        "tierPrices": {
          "small": 1472.5,
          "tier2": 1395,
          "preferred": 1317.5
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 325,
        "tierPrices": {
          "small": 308.75,
          "tier2": 292.5,
          "preferred": 276.25
        },
        "gals": 3
      }
    ]
  },
  "polyurea_slow": {
    "name": "Polyurea Basecoat (Slow)",
    "materialCategory": "polyurea",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 750,
        "tierPrices": {
          "small": 712.5,
          "tier2": 675,
          "preferred": 637.5
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 156,
        "tierPrices": {
          "small": 148.2,
          "tier2": 140.4,
          "preferred": 132.6
        },
        "gals": 3
      }
    ]
  },
  "polyurea_med": {
    "name": "Polyurea Basecoat (Medium)",
    "materialCategory": "polyurea",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 750,
        "tierPrices": {
          "small": 684,
          "tier2": 648,
          "preferred": 612
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 156,
        "tierPrices": {
          "small": 142.5,
          "tier2": 135,
          "preferred": 127.5
        },
        "gals": 3
      }
    ]
  },
  "polyurea_fast": {
    "name": "Polyurea Basecoat (Fast)",
    "materialCategory": "polyurea",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 750,
        "tierPrices": {
          "small": 712.5,
          "tier2": 675,
          "preferred": 637.5
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 156,
        "tierPrices": {
          "small": 148.2,
          "tier2": 140.4,
          "preferred": 132.6
        },
        "gals": 3
      }
    ]
  },
  "h20_ziothane_gloss": {
    "name": "H20 Ziothane (Gloss)",
    "materialCategory": "urethane",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1450,
        "tierPrices": {
          "small": 1377.5,
          "tier2": 1305,
          "preferred": 1232.5
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 330,
        "tierPrices": {
          "small": 313.5,
          "tier2": 297,
          "preferred": 280.5
        },
        "gals": 3
      }
    ]
  },
  "h20_ziothane_low_gloss": {
    "name": "H20 Ziothane (Low Gloss)",
    "materialCategory": "urethane",
    "kits": [
      {
        "size": "15 gal",
        "msrp": 1450,
        "tierPrices": {
          "small": 1377.5,
          "tier2": 1305,
          "preferred": 1232.5
        },
        "gals": 15
      },
      {
        "size": "3 gal",
        "msrp": 330,
        "tierPrices": {
          "small": 313.5,
          "tier2": 297,
          "preferred": 280.5
        },
        "gals": 3
      }
    ]
  },
  "ez_top_85": {
    "name": "E-Z Top 85",
    "materialCategory": "urethane",
    "kits": [
      {
        "size": "1 gal",
        "msrp": 158.8,
        "tierPrices": {
          "small": 130.77,
          "tier2": 121.43,
          "preferred": 112.09
        },
        "gals": 1
      }
    ]
  },
  "wearmax": {
    "name": "WearMax (goes in E-Z Top 85)",
    "materialCategory": "urethane",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "1 unit",
        "msrp": 26.74,
        "tierPrices": {
          "small": 22.02,
          "tier2": 20.45,
          "preferred": 18.88
        },
        "gals": 0
      }
    ]
  },
  "hypercure": {
    "name": "HyperCURE",
    "materialCategory": "repair",
    "kits": [
      {
        "size": "0.5 gal",
        "msrp": 100.1,
        "tierPrices": {
          "small": 94.5,
          "tier2": 87.5,
          "preferred": 81.9
        },
        "gals": 0.5
      }
    ]
  },
  "pe85_joint_fill": {
    "name": "PE-85 (Twin Tube Polyurea Joint Fill)",
    "materialCategory": "repair",
    "kits": [
      {
        "size": "22 oz",
        "msrp": 111.54,
        "tierPrices": {
          "small": 52.65,
          "tier2": 48.75,
          "preferred": 45.63
        },
        "gals": 0
      }
    ]
  },
  "patch_pro_10x": {
    "name": "Patch Pro 10X (ET)",
    "materialCategory": "repair",
    "kits": [
      {
        "size": "2 gal",
        "msrp": 146.07,
        "tierPrices": {
          "small": 133.41,
          "tier2": 126.59,
          "preferred": 119.78
        },
        "gals": 2
      }
    ]
  },
  "flake_vinyl_quarter": {
    "name": "Vinyl — 1/4\" (stocking colors)",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "40lb box",
        "msrp": 95,
        "tierPrices": {
          "small": 90.25,
          "tier2": 85.5,
          "preferred": 80.75
        },
        "gals": 0,
        "lbs": 40
      }
    ]
  },
  "flake_vinyl_eighth": {
    "name": "Vinyl — 1/8\" (stocking colors)",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "40lb box",
        "msrp": 99,
        "tierPrices": {
          "small": 94.05,
          "tier2": 89.1,
          "preferred": 84.15
        },
        "gals": 0,
        "lbs": 40
      }
    ]
  },
  "flake_hybrid": {
    "name": "Hybrid",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "40lb box",
        "msrp": 122,
        "tierPrices": {
          "small": 115.9,
          "tier2": 109.8,
          "preferred": 103.7
        },
        "gals": 0,
        "lbs": 40
      }
    ]
  },
  "flake_marble": {
    "name": "Marble",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "40lb box",
        "msrp": 99,
        "tierPrices": {
          "small": 94.05,
          "tier2": 89.1,
          "preferred": 84.15
        },
        "gals": 0,
        "lbs": 40
      }
    ]
  },
  "flake_mica": {
    "name": "Mica",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "10lb box",
        "msrp": 250,
        "tierPrices": {
          "small": 237.5,
          "tier2": 225,
          "preferred": 212.5
        },
        "gals": 0,
        "lbs": 10
      }
    ]
  },
  "permaseal_clear": {
    "name": "Permaseal — Clear Urethane (5 Gal Pail)",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "5 gal pail",
        "msrp": 336.45,
        "tierPrices": {
          "small": 302.81,
          "tier2": 289.35,
          "preferred": 269.16
        },
        "gals": 5
      }
    ]
  },
  "flake_fan_deck": {
    "name": "Small Fan Deck — Color Deck of Flakes - FGP",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "1 deck",
        "msrp": 52.5,
        "tierPrices": {
          "small": 47.95,
          "tier2": 45.5,
          "preferred": 43.05
        },
        "gals": 0
      }
    ]
  },
  "flake_suitcase": {
    "name": "Large Suitcase Colors — All Color options & Misc. Floors",
    "materialCategory": "flake",
    "kits": [
      {
        "size": "1 suitcase",
        "msrp": 298.5,
        "tierPrices": {
          "small": 272.63,
          "tier2": 258.7,
          "preferred": 244.77
        },
        "gals": 0
      }
    ]
  },
  "epoly_pigment_black": {
    "name": "E-Poly Pigment — Black",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 39.8,
        "tierPrices": {
          "preferred": 37.81
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_metal_gray": {
    "name": "E-Poly Pigment — Metal Gray",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 40.2,
        "tierPrices": {
          "preferred": 38.19
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_medium_gray": {
    "name": "E-Poly Pigment — Medium Gray",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 40.9,
        "tierPrices": {
          "preferred": 38.86
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_sable_gray": {
    "name": "E-Poly Pigment — Sable Gray",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 44.3,
        "tierPrices": {
          "preferred": 42.09
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_white": {
    "name": "E-Poly Pigment — White",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 52.6,
        "tierPrices": {
          "preferred": 49.97
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_dover_beige": {
    "name": "E-Poly Pigment — Dover Beige",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 44.5,
        "tierPrices": {
          "preferred": 42.28
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_tan": {
    "name": "E-Poly Pigment — Tan",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 43.2,
        "tierPrices": {
          "preferred": 41.04
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "epoly_pigment_nonstock": {
    "name": "E-Poly Pigment (specialty tint)",
    "materialCategory": "epoly_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "32oz",
        "msrp": 39.8,
        "tierPrices": {
          "preferred": 37.81
        },
        "pricingModel": "accessory",
        "gals": 0.25
      }
    ]
  },
  "metallic_mica_4oz": {
    "name": "Metallic Pigment (stocking colors)",
    "materialCategory": "metallic_pigment",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "4oz",
        "msrp": 12.5,
        "tierPrices": {
          "preferred": 11.88
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "quartz_agg": {
    "name": "Quartz (stocking colors)",
    "materialCategory": "quartz",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "50lb bag",
        "msrp": 25,
        "tierPrices": {
          "preferred": 23.75
        },
        "pricingModel": "accessory",
        "lbs": 50
      }
    ]
  },
  "spike_shoes_medium": {
    "name": "Spike Shoes — Medium",
    "materialCategory": "spike_shoes",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "pair",
        "msrp": 145,
        "tierPrices": {
          "preferred": 137.75
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "spike_shoes_large": {
    "name": "Spike Shoes — Large",
    "materialCategory": "spike_shoes",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "pair",
        "msrp": 145,
        "tierPrices": {
          "preferred": 137.75
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "spike_shoes_xl": {
    "name": "Spike Shoes — Xtra Large",
    "materialCategory": "spike_shoes",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "pair",
        "msrp": 145,
        "tierPrices": {
          "preferred": 137.75
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_qt_lid": {
    "name": "1 Qt Multi-Mix Container Lid",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 0.48,
        "tierPrices": {
          "preferred": 0.46
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_qt_container": {
    "name": "1 Qt Multi-Mix Container — Quart",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 1.05,
        "tierPrices": {
          "preferred": 1
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_caution_tape": {
    "name": "1000'x3\" Caution Tape",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 27.01,
        "tierPrices": {
          "preferred": 25.66
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_mixing_stick_12": {
    "name": "12\" Mixing Stick — No Finger Grip",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "100/box",
        "msrp": 6.48,
        "tierPrices": {
          "preferred": 6.16
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_coater_refill_12": {
    "name": "12\" Woven Floor Coater Refill",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 14.45,
        "tierPrices": {
          "preferred": 13.73
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_coater_refill_18_nyl": {
    "name": "18\" Floor Coater Refill Nylfoam",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 14.78,
        "tierPrices": {
          "preferred": 14.04
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_coater_refill_18_woven": {
    "name": "18\" Floor Coater Refill Woven",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 18.75,
        "tierPrices": {
          "preferred": 17.81
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_painters_tape": {
    "name": "2\" — 60 yd Roll of Blue Painters Tape",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "6/box",
        "msrp": 79.5,
        "tierPrices": {
          "preferred": 75.53
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_chip_brush": {
    "name": "3\" Chip Brush",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "12/box",
        "msrp": 9.07,
        "tierPrices": {
          "preferred": 8.62
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_turbo_cup": {
    "name": "4.5\" 9 Segment Turbo Cup Wheel",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 49.99,
        "tierPrices": {
          "preferred": 47.49
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_saw_blade": {
    "name": "4.5\" X .080 Premium Segmented Saw Blade",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 25,
        "tierPrices": {
          "preferred": 23.75
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_arrow_cup": {
    "name": "7\" Arrow Segment Cup Wheel",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 95,
        "tierPrices": {
          "preferred": 90.25
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_turbo_blade": {
    "name": "7\" Turbo Diamond Blade (24) Segmented",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 100,
        "tierPrices": {
          "preferred": 95
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_cloth_gloves": {
    "name": "Cloth Gloves",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "12/box",
        "msrp": 12,
        "tierPrices": {
          "preferred": 11.4
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_dust_mask": {
    "name": "Dust Mask",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "20/box",
        "msrp": 33.49,
        "tierPrices": {
          "preferred": 31.82
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_dust_pan": {
    "name": "Dust Pan",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 24.95,
        "tierPrices": {
          "preferred": 23.7
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_ear_muffs": {
    "name": "Ear Muffs",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 14.43,
        "tierPrices": {
          "preferred": 13.71
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_garbage_bags": {
    "name": "Garbage Bags",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "50/box",
        "msrp": 46.65,
        "tierPrices": {
          "preferred": 44.32
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_dust_shroud_hose": {
    "name": "Grinding Dust Shroud Hose 18\"",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 34.22,
        "tierPrices": {
          "preferred": 32.51
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_sand_screen": {
    "name": "Norton Sand Screen Disc 100 Grit",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 9.3,
        "tierPrices": {
          "preferred": 8.84
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_vapor_respirator": {
    "name": "Organic Vapor Repirator (FTC)",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 38.84,
        "tierPrices": {
          "preferred": 36.9
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_rags": {
    "name": "Rags 80-100 rags per box",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "100/box",
        "msrp": 25.83,
        "tierPrices": {
          "preferred": 24.54
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_safety_glasses": {
    "name": "Safety Glasses",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 5.42,
        "tierPrices": {
          "preferred": 5.15
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_nitrile_gloves": {
    "name": "SemperForce HD 5 Mil Black Nitrile Disposable gloves",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "100/box",
        "msrp": 10.61,
        "tierPrices": {
          "preferred": 10.08
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_spikes_pair": {
    "name": "Spikes — per pair",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "pair",
        "msrp": 23.75,
        "tierPrices": {
          "preferred": 22.56
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_hand_sprayer": {
    "name": "0.5 Ga Hand Sprayer",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 11.65,
        "tierPrices": {
          "preferred": 11.07
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_horsehair_14": {
    "name": "14\" Horsehair Brush Replacement (Brush ONLY)",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 35.57,
        "tierPrices": {
          "preferred": 33.79
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_vacuum_head_14": {
    "name": "14\" Vacuum Head Frame with Horsehair Brush (TOOL)",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 123.39,
        "tierPrices": {
          "preferred": 117.22
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_horsehair_16": {
    "name": "16\" Horsehair Brush Replacement (Brush ONLY)",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 52.62,
        "tierPrices": {
          "preferred": 49.99
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_vacuum_hose": {
    "name": "2\" X 25\" Crush Proof Vacuum Hose",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 109.07,
        "tierPrices": {
          "preferred": 103.62
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_trowel": {
    "name": "11\"x4.5\" Trowel",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 14.28,
        "tierPrices": {
          "preferred": 13.57
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_bona_coater": {
    "name": "12\" Bona Lightweight T-Bar Floor Coater",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 32.55,
        "tierPrices": {
          "preferred": 30.92
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_scraper_14": {
    "name": "14\" Wide Floor Scraper & Stripper",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 40,
        "tierPrices": {
          "preferred": 38
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_big_ben_frame": {
    "name": "18\" Big Ben Roller Frame — sold each",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 11.37,
        "tierPrices": {
          "preferred": 10.8
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_bigfoot_heavy": {
    "name": "18\" Big Foot Floor Coater Heavyweight",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 50.46,
        "tierPrices": {
          "preferred": 47.94
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_bigfoot_light": {
    "name": "18\" Big Foot Floor Coater Lightweight",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 43.78,
        "tierPrices": {
          "preferred": 41.59
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_broom_head_23": {
    "name": "23\" Blue Soft Broom Head",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 26.34,
        "tierPrices": {
          "preferred": 25.02
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_flat_squeegee": {
    "name": "24\" Flat Squeegee",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 29.98,
        "tierPrices": {
          "preferred": 28.48
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_speed_squeegee_quarter": {
    "name": "24\" Speed Squeegee 1/4\" Notched",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 39.31,
        "tierPrices": {
          "preferred": 37.34
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_speed_squeegee_316": {
    "name": "24\" Speed Squeegee 3/16\" Notched",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 39.31,
        "tierPrices": {
          "preferred": 37.34
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_broom_29": {
    "name": "29\" Blue Soft Broom",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 31.12,
        "tierPrices": {
          "preferred": 29.56
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_weenie_frame": {
    "name": "4.5\" Roller Frame — Weenie Roller",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 4.56,
        "tierPrices": {
          "preferred": 4.33
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_measuring_bucket": {
    "name": "5 Qt Measuring Bucket — Quart",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 2.59,
        "tierPrices": {
          "preferred": 2.46
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_bucket_buster": {
    "name": "Bucket Buster",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 53.34,
        "tierPrices": {
          "preferred": 50.67
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_extension_pole": {
    "name": "Extension Pole 4-8'",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 20.45,
        "tierPrices": {
          "preferred": 19.43
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_broom_handle": {
    "name": "Steel Broom Handle",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 13.88,
        "tierPrices": {
          "preferred": 13.19
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_9_frame": {
    "name": "Wooster 9\" Roller Frame",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 5,
        "tierPrices": {
          "preferred": 4.75
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_bigmouth_bucket": {
    "name": "2 Ga Bigmouth Bucket (4)",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "4/box",
        "msrp": 47.43,
        "tierPrices": {
          "preferred": 45.06
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_sherlock": {
    "name": "Wooster 18\" Sherlock Wide Boy Frame",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 21.48,
        "tierPrices": {
          "preferred": 20.41
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_pro_dooz_18": {
    "name": "Wooster Pro Doo Z 18\" 3/4\" Nap Roller Cover",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "6/box",
        "msrp": 65.45,
        "tierPrices": {
          "preferred": 62.18
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_super_doo_18": {
    "name": "Wooster Super Doo 18\" 3/8\" Nap Roller Cover",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "6/box",
        "msrp": 43.5,
        "tierPrices": {
          "preferred": 41.33
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_super_dooz_9_34": {
    "name": "Wooster Super Doo Z 9\" 3/4\" Nap Roller cover",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "12/box",
        "msrp": 47.14,
        "tierPrices": {
          "preferred": 44.78
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_wooster_super_dooz_9_38": {
    "name": "Wooster Super Doo Z 9\" 3/8\" Nap Roller Cover",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "12/box",
        "msrp": 34.18,
        "tierPrices": {
          "preferred": 32.47
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_purdy_frame": {
    "name": "Purdy 18\" Revolution Roller Frame",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 49.37,
        "tierPrices": {
          "preferred": 47.24
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_trash_bags_42": {
    "name": "HD Contractor Trash Bags — 42 Gallon (Box of 22)",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 15.25,
        "tierPrices": {
          "preferred": 14.59
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_helix_paddle_1": {
    "name": "1 Gal Helix Mixing Paddle",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 10.52,
        "tierPrices": {
          "preferred": 9.27
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_helix_paddle_5": {
    "name": "5 Gal Helix Mixing Paddle",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 11.77,
        "tierPrices": {
          "preferred": 10.37
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_weenie_frame_12": {
    "name": "12\" Roller Frame — Weenie Roller",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 4.17,
        "tierPrices": {
          "preferred": 3.99
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_weenie_frame_16": {
    "name": "16\" Roller Frame — Weenie Roller",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 6.39,
        "tierPrices": {
          "preferred": 6.12
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_weenie_covers_6": {
    "name": "6\" Weenie Roller Covers — 6 pack (1/2\" nap)",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 7.41,
        "tierPrices": {
          "preferred": 7.09
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "anc_roller_cover_18": {
    "name": "18\" Contractor Woven Roller Cover, 3/8\" Nap",
    "materialCategory": "tools",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 12.37,
        "tierPrices": {
          "preferred": 11.84
        },
        "pricingModel": "accessory"
      }
    ]
  },
  "silica_sand": {
    "name": "Dry Silica Sand — 50 lb Bag",
    "materialCategory": "supplies",
    "pricingModel": "accessory",
    "kits": [
      {
        "size": "ea",
        "msrp": 15.83,
        "tierPrices": {
          "preferred": 12.38
        },
        "pricingModel": "accessory",
        "lbs": 50
      }
    ]
  }
};

function _alias(targetKey, name, kitOverrides) {
  const base = _BASE_PRODUCTS[targetKey];
  if (!base) return null;
  const kits = kitOverrides
    ? base.kits.map((k, i) => (i === 0 ? { ...k, ...kitOverrides } : { ...k }))
    : base.kits.map((k) => ({ ...k, tierPrices: k.tierPrices ? { ...k.tierPrices } : undefined }));
  return { ...base, name, kits };
}

export const PRODUCTS = {
  ..._BASE_PRODUCTS,
  hyperbond: _alias("hyperbond_clear", "HyperBOND (Clear)"),
  dt454_turbo: _alias("dt454_clear", "DT 454 (Clear) — Turbo"),
  aspartic85: _alias("aspartic85_slow_low", "Aspartic 85 Slow Go (Low Odor)"),
  marblemax: _alias("hyperflow", "MarbleMax"),
  wearmax_3lb: _alias("wearmax", "WearMax — 3 lb jar", { size: "3 lb jar", lbs: 3 }),
  flake_14: _alias("flake_vinyl_quarter", 'Decorative Flake 1/4"'),
  tool_spike_shoes: _alias("spike_shoes_medium", "Spike Shoes (pair)"),
};

export function resolveEpolyProductKey(baseCoatColor) {
  const c = baseCoatColor || "Black";
  const slug = c.toLowerCase().replace(/\s+/g, "_");
  const key = `epoly_pigment_${slug}`;
  if (PRODUCTS[key]) return key;
  return "epoly_pigment_nonstock";
}

export function resolveLayerProductKey(layer, answers) {
  if (layer.key !== "epoly_pigment") return layer.key;
  return resolveEpolyProductKey(answers?.baseCoatColor || answers?.color);
}
